name: orange3-toxfairy
channels:
  - conda-forge
  - default
dependencies:
  - AnyQt~=0.2.0
  - matplotlib~=3.9.0
  - numpy~=1.26.0
  - orange-widget-base~=4.25
  - orange3~=3.38
  - pandas~=2.2.0
  - pip~=24.3.0
  - plotly~=5.24.0
  - pyqt~=5.15.0
  - python>=3.10,<3.13
  - r-abind~=1.4_5
  - r-biocmanager~=1.30.21
  - r-brio~=1.1.5
  - r-cardata~=3.0_5
  - r-car~=3.1_2
  - r-desc~=1.4.2
  - r-diffobj~=0.3.5
  - r-essentials~=4.1
  - r-lme4~=1.1_35.5
  - r-matrixmodels~=0.5_1
  - r-minqa~=1.2.7
  - r-nloptr~=2.0.3
  - r-pbkrtest~=0.5.2
  - r-pkgbuild~=1.4.0
  - r-pkgload~=1.3.2
  - r-praise~=1.0.0
  - r-quantreg~=5.98
  - r-rprojroot~=2.0.3
  - r-sparsem~=1.84
  - r-testthat~=3.2.1.1
  - r-waldo~=0.5.1
  - rpy2~=3.5.0
  - r~=4.0
  - scikit-learn~=1.5.0
  - scipy~=1.14.0
  - setuptools~=75.6.0
  - pip:
    - -e toxfairy
    - -e .
