name: toxpi_orange_tests_
channels:
  - bioconda
  - conda-forge
  - default
dependencies:
  - python==3.10
  - AnyQt
  - bioconductor-biocgenerics
  - bioconductor-s4vectors
  - matplotlib
  - numpy
  - orange-widget-base
  - orange3~=3.0
  - pandas
  - pip
  - pyqt
  - r
  - r-abind
  - r-brio
  - r-car
  - r-cardata
  - r-desc
  - r-diffobj
  - r-essentials
  - r-lme4
  - r-matrixmodels
  - r-minqa
  - r-nloptr
  - r-pbkrtest
  - r-pkgbuild
  - r-pkgload
  - r-praise
  - r-quantreg
  - r-rprojroot
  - r-sparsem
  - r-testthat
  - r-waldo
  - rpy2==3.5.7
  - scikit-learn
  - scipy
  - setuptools
  - pip:
    - -e tox5_preprocessing
    - -e .
